// Autogenerated with obj_to_js.py from ../assignment-8/bush.obj at 2023-12-10 18:05:51.449434 by rochelleli
// See https://github.com/elbrandt/ObjToJs for more info

// unique vertex positions  : 8
// unique vertex normals    : 2
// unique vertex tex coords : 4
// total vertices           : 8
// total normals            : 8
// total tex coords         : 8
// triangles                : 4
// bb_min                   : [2.070117, 0.396138, -1.440835]
// bb_max                   : [2.51475, 0.878378, -0.996202]

// triangleIndices type     : Uint8Array
// the object
var bush = new Object();

// element index array
bush.triangleIndices = new Uint8Array([0, 1, 2, 0, 2, 3, 4, 5, 6, 4, 6, 7]);

// vertex positions
bush.vertexPos = new Float32Array([ 2.385787, 0.878378, -0.996203, 2.385784, 0.396138, -0.996202, 2.19908, 0.396138, -1.440833, 2.199084, 0.878378, -1.440835, 2.514748, 0.878378, -1.311872, 2.51475, 0.396138, -1.311868, 2.070118, 0.396138, -1.125165, 2.070117, 0.878378, -1.125168]);

// vertex normals
bush.vertexNormals = new Float32Array([ 0.922, -0.0, -0.3872, 0.922, -0.0, -0.3872, 0.922, -0.0, -0.3872, 0.922, -0.0, -0.3872, -0.3872, -0.0, -0.922, -0.3872, -0.0, -0.922, -0.3872, -0.0, -0.922, -0.3872, -0.0, -0.922]);

// vertex texture coordinates
bush.vertexTextureCoords = new Float32Array([ 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0]);

