// Autogenerated with obj_to_js.py from ../assignment-8/flowers.obj at 2023-12-10 20:34:51.102919 by rochelleli
// See https://github.com/elbrandt/ObjToJs for more info

// unique vertex positions  : 12
// unique vertex normals    : 3
// unique vertex tex coords : 12
// total vertices           : 12
// total normals            : 12
// total tex coords         : 12
// triangles                : 6
// bb_min                   : [-1.396385, 0.461194, -2.80877]
// bb_max                   : [1.301739, 0.740849, -2.80877]

// triangleIndices type     : Uint8Array
// the object
var flowers = new Object();

// element index array
flowers.triangleIndices = new Uint8Array([0, 1, 2, 0, 2, 3, 4, 5, 6, 4, 6, 7, 8, 9, 10, 8, 10, 11]);

// vertex positions
flowers.vertexPos = new Float32Array([ 0.833746, 0.461194, -2.80877, 1.301739, 0.461194, -2.80877, 1.301739, 0.740849, -2.80877, 0.833746, 0.740849, -2.80877, -0.275148, 0.461194, -2.80877, 0.192844, 0.461194, -2.80877, 0.192844, 0.740849, -2.80877, -0.275148, 0.740849, -2.80877, -1.396385, 0.461194, -2.80877, -0.928393, 0.461194, -2.80877, -0.928393, 0.740849, -2.80877, -1.396385, 0.740849, -2.80877]);

// vertex normals
flowers.vertexNormals = new Float32Array([ -0.0, -0.0, 1.0, -0.0, -0.0, 1.0, -0.0, -0.0, 1.0, -0.0, -0.0, 1.0, -0.0, -0.0, 1.0, -0.0, -0.0, 1.0, -0.0, -0.0, 1.0, -0.0, -0.0, 1.0, -0.0, -0.0, 1.0, -0.0, -0.0, 1.0, -0.0, -0.0, 1.0, -0.0, -0.0, 1.0]);

// vertex texture coordinates
flowers.vertexTextureCoords = new Float32Array([ 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0]);

