// Autogenerated with obj_to_js.py from ../assignment-8/grass-2.obj at 2023-12-09 16:36:45.312271 by rochelleli
// See https://github.com/elbrandt/ObjToJs for more info

// unique vertex positions  : 8
// unique vertex normals    : 2
// unique vertex tex coords : 4
// total vertices           : 8
// total normals            : 8
// total tex coords         : 8
// triangles                : 4
// bb_min                   : [4.173488, -0.005815, -2.234656]
// bb_max                   : [4.618212, 0.476424, -1.789932]

// triangleIndices type     : Uint8Array
// the object
var grassTwo = new Object();

// aligned bounding box extents
grassTwo.bboxMin = new Float32Array([4.173488, -0.005815, -2.234656]);
grassTwo.bboxMax = new Float32Array([4.618212, 0.476424, -1.789932]);

// element index array
grassTwo.triangleIndices = new Uint8Array([0, 1, 2, 0, 2, 3, 4, 5, 6, 4, 6, 7]);

// vertex positions
grassTwo.vertexPos = new Float32Array([ 4.302609, 0.476424, -1.789932, 4.302606, -0.005815, -1.789933, 4.489091, -0.005815, -2.234656, 4.489094, 0.476424, -2.234655, 4.618212, 0.476424, -1.919053, 4.618211, -0.005815, -1.91905, 4.173488, -0.005815, -2.105535, 4.173489, 0.476424, -2.105538]);

// vertex normals
grassTwo.vertexNormals = new Float32Array([ 0.9222, -0.0, 0.3867, 0.9222, -0.0, 0.3867, 0.9222, -0.0, 0.3867, 0.9222, -0.0, 0.3867, 0.3867, -0.0, -0.9222, 0.3867, -0.0, -0.9222, 0.3867, -0.0, -0.9222, 0.3867, -0.0, -0.9222]);

// vertex texture coordinates
grassTwo.vertexTextureCoords = new Float32Array([ 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0]);

