// Autogenerated with obj_to_js.py from ../assignment-8/ground.obj at 2023-12-10 19:23:44.600261 by rochelleli
// See https://github.com/elbrandt/ObjToJs for more info

// unique vertex positions  : 4
// unique vertex normals    : 1
// unique vertex tex coords : 4
// total vertices           : 4
// total normals            : 4
// total tex coords         : 4
// triangles                : 2
// bb_min                   : [-5.516542, 0.0, -5.516542]
// bb_max                   : [5.516542, 0.0, 5.516542]

// triangleIndices type     : Uint8Array
// the object
var ground = new Object();

// element index array
ground.triangleIndices = new Uint8Array([0, 1, 2, 0, 2, 3]);

// vertex positions
ground.vertexPos = new Float32Array([ -5.516542, 0.0, 5.516542, 5.516542, 0.0, 5.516542, 5.516542, 0.0, -5.516542, -5.516542, 0.0, -5.516542]);

// vertex normals
ground.vertexNormals = new Float32Array([ -0.0, 1.0, -0.0, -0.0, 1.0, -0.0, -0.0, 1.0, -0.0, -0.0, 1.0, -0.0]);

// vertex texture coordinates
ground.vertexTextureCoords = new Float32Array([ 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0]);

