// Autogenerated with obj_to_js.py from models/sqaure.obj at 2023-12-04 21:40:46.856939 by Patron
// See https://github.com/elbrandt/ObjToJs for more info

// unique vertex positions  : 4
// unique vertex normals    : 1
// unique vertex tex coords : 4
// total vertices           : 4
// total normals            : 4
// total tex coords         : 4
// triangles                : 2
// bb_min                   : [-4.26895, 0.0, -4.26895]
// bb_max                   : [4.26895, 0.0, 4.26895]

// triangleIndices type     : Uint8Array
// the object
var planel = new Object();

// aligned bounding box extents
planel.bboxMin = new Float32Array([-4.26895, 0.0, -4.26895]);
planel.bboxMax = new Float32Array([4.26895, 0.0, 4.26895]);

// element index array
planel.triangleIndices = new Uint32Array([0, 1, 2, 0, 2, 3]);

// vertex positions
planel.vertexPos = new Float32Array([ -4.26895, 0.0, 4.26895, 4.26895, 0.0, 4.26895, 4.26895, 0.0, -4.26895, -4.26895, 0.0, -4.26895]);

// vertex normals
planel.vertexNormals = new Float32Array([ -0.0, 1.0, -0.0, -0.0, 1.0, -0.0, -0.0, 1.0, -0.0, -0.0, 1.0, -0.0]);

// vertex texture coordinates
planel.vertexTextureCoords = new Float32Array([ 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0]);

